components:
  - ARCHEAN_beacon.Beacon
recipes:
  - label: Beacon
    context: avatar
    category: components
    time: 30
    input:
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Panel: 1
      ARCHEAN_parts.Screw: 10
      ARCHEAN_parts.Wire: 10
      ARCHEAN_parts.Magnet: 10
      ARCHEAN_parts.Capacitor: 10
      ARCHEAN_parts.Connector: 2
    output:
      ARCHEAN_beacon.Beacon: 1
