components:
  - ARCHEAN_ownership.OwnerPad

recipes:

  - label: OwnerPad
    context: avatar
    category: components
    time: 10
    input:
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Panel: 1
      ARCHEAN_parts.Screw: 10
      ARCHEAN_parts.Wire: 10
      ARCHEAN_parts.LED: 10
    output:
      ARCHEAN_ownership.OwnerPad: 1
