# ores:
#   - ARCHEAN_celestial.Aluminium: Al
#   - ARCHEAN_celestial.Chrome: Cr
#   - ARCHEAN_celestial.Copper: Cu
#   - ARCHEAN_celestial.Gold: Au
#   - ARCHEAN_celestial.Iron: Fe
#   - ARCHEAN_celestial.Lead: Pb
#   - ARCHEAN_celestial.Nickel: Ni
#   - ARCHEAN_celestial.Silicon: Si
#   - ARCHEAN_celestial.Silver: Ag
#   - ARCHEAN_celestial.Tin: Sn
#   - ARCHEAN_celestial.Titanium: Ti
#   - ARCHEAN_celestial.Tungsten: W
#   - ARCHEAN_celestial.Uranium: U
#   - ARCHEAN_celestial.Carbon: C

# tools:
#   - ARCHEAN_celestial.RockRakeTool

components:
  - ARCHEAN_celestial.NavInstrument
  - ARCHEAN_celestial.SolarPanel
  - ARCHEAN_celestial.MiningDrill
  - ARCHEAN_celestial.OreScanner

recipes:

  - context: crusher
    time: 0.02
    input: ARCHEAN_celestial.Rock
    output:
      ARCHEAN_celestial.Aluminium: input.composition.Al
      ARCHEAN_celestial.Chrome: input.composition.Cr
      ARCHEAN_celestial.Copper: input.composition.Cu
      ARCHEAN_celestial.Gold: input.composition.Au
      ARCHEAN_celestial.Iron: input.composition.Fe
      ARCHEAN_celestial.Lead: input.composition.Pb
      ARCHEAN_celestial.Nickel: input.composition.Ni
      ARCHEAN_celestial.Silicon: input.composition.Si
      ARCHEAN_celestial.Silver: input.composition.Ag
      ARCHEAN_celestial.Tin: input.composition.Sn
      ARCHEAN_celestial.Titanium: input.composition.Ti
      ARCHEAN_celestial.Tungsten: input.composition.W
      ARCHEAN_celestial.Uranium: input.composition.U
      ARCHEAN_celestial.Carbon: input.composition.C
      ARCHEAN_celestial.Cheese: input.composition.Ch
  
  - label: RockRakeTool
    context: crafter
    category: tools
    time: 10
    input:
      ARCHEAN_celestial.Iron: 100
      ARCHEAN_parts.Screw: 10
    output:
      ARCHEAN_celestial.RockRakeTool: 1
  
  - label: NavInstrument
    context: crafter
    category: components
    time: 30
    input:
      ARCHEAN_parts.Circuit: 10
      ARCHEAN_parts.Casing: 2
      ARCHEAN_parts.Panel: 1
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Wire: 10
      ARCHEAN_parts.LED: 100
      ARCHEAN_parts.Magnet: 10
      ARCHEAN_parts.Capacitor: 10
      ARCHEAN_celestial.Gold: 10
      ARCHEAN_parts.Connector: 2
    output:
      ARCHEAN_celestial.NavInstrument: 1
  
  - label: SolarPanel
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Panel: 1
      ARCHEAN_parts.Connector: 3
      ARCHEAN_celestial.Silicon: 1000
    output:
      ARCHEAN_celestial.SolarPanel: 1
  
  - label: SolarSensor
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Connector: 1
      ARCHEAN_parts.Diode: 10
      ARCHEAN_celestial.Silicon: 10
    output:
      ARCHEAN_celestial.SolarSensor: 1
  
  - label: MiningDrill
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 3
      ARCHEAN_parts.Motor: 2
      ARCHEAN_parts.Disk: 10
      ARCHEAN_celestial.Tungsten: 1
    output:
      ARCHEAN_celestial.MiningDrill: 1
  
  - label: OreScanner
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 2
      ARCHEAN_parts.Magnet: 1
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Capacitor: 1
    output:
      ARCHEAN_celestial.OreScanner: 1
  
  - label: TerrainScanner
    context: crafter
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 2
      ARCHEAN_parts.Magnet: 1
      ARCHEAN_parts.Circuit: 1
      ARCHEAN_parts.Capacitor: 1
    output:
      ARCHEAN_celestial.TerrainScanner: 1
  