components:
  - ARCHEAN_rcs.RCS
recipes:
  - label: RCS
    context: avatar
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 1
      ARCHEAN_celestial.Aluminium: 10
    output:
      ARCHEAN_rcs.RCS: 1
