components:
  - ARCHEAN_anchor.GroundAnchor
recipes:
  - label: GroundAnchor
    context: avatar
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Connector: 1
      ARCHEAN_celestial.Iron: 1000
    output:
      ARCHEAN_anchor.GroundAnchor: 1
