components:
  - ARCHEAN_wheel.Wheel
  - ARCHEAN_wheel.SmallWheel

recipes:

  - label: Wheel
    context: avatar
    category: components
    time: 10
    input:
      ARCHEAN_parts.Casing: 2
      ARCHEAN_parts.Screw: 100
      ARCHEAN_parts.Plastic: 100
      ARCHEAN_parts.Connector: 3
      ARCHEAN_parts.Motor: 1
      ARCHEAN_parts.Disk: 1
    output:
      ARCHEAN_wheel.Wheel: 1
  
  - label: SmallWheel
    context: avatar
    category: components
    time: 5
    input:
      ARCHEAN_parts.Casing: 1
      ARCHEAN_parts.Screw: 10
      ARCHEAN_parts.Plastic: 10
      ARCHEAN_parts.Connector: 1
      ARCHEAN_parts.Disk: 1
    output:
      ARCHEAN_wheel.SmallWheel: 1
